import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/ui/header";
import { Sidebar } from "@/components/ui/sidebar";
import { ThemeProvider } from "next-themes";
import { Suspense } from "react";

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-main',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Movies.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} antialiased`} suppressHydrationWarning>
      <body cz-shortcut-listen="true" >
        <ThemeProvider attribute='class' enableSystem defaultTheme="system">
          <Suspense fallback={<>Loading...</>}>
            <Header />
            <main className="w-full min-h-full grid grid-cols-1 md:grid-cols-[200px_1fr] md:pt-10 text-zinc-600 dark:text-zinc-300 transition-all duration-700">
              <Sidebar />
              {children}
            </main>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
